steps:
  - name: 1. Checkout code
    uses: actions/checkout@v3

  - name: 2. Set up Node
    uses: actions/setup-node@v3
    with:
      node-version: 18

  - name: 3. Install dependencies
    # FIX: Setting working-directory to the project sub-folder
    run: npm install
    working-directory: ./HomzNOffiz_frontend

  - name: 4. Build React App
    # FIX: Setting working-directory to the project sub-folder
    run: npm run build
    working-directory: ./HomzNOffiz_frontend

  - name: 5. Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: 6. Build Docker Image
    # FIX: Setting working-directory to the project sub-folder. This assumes your Dockerfile is also inside this folder.
    run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-newproject .
    working-directory: ./HomzNOffiz_frontend

  - name: 7. Push Docker Image
    # This step doesn't need working-directory as the image name is fully qualified.
    run: docker push ${{ secrets.DOCKER_USERNAME }}/react-newproject:latest
