name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./newproject
        run: npm install

      # Step 4: Build React App
      - name: Build React App
        working-directory: ./newproject
        run: CI=false npm run build

      # Step 5: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RachnaRajak040 }}
          password: ${{ secrets.dckr_pat_qVGWeHiCMugjREtXF8zydGuK3S0 }}

      # Step 6: Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/react-newproject:latest ./newproject

      # Step 7: Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/react-newproject:latest
