name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 3. Install dependencies
        working-directory: ./client
        run: npm install

      - name: 4. Build React App
        working-directory: ./client
        run: CI=false npm run build

      - name: 5. Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.RACHNARAJAK040 }}

      - name: 6. Build Docker Image
        working-directory: ./client
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-newproject:latest .

      - name: 7. Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-newproject:latest